--- 
- sysctl:
    name: vm.max_map_count
    value: '262144'
    state: present
    sysctl_set: yes
    reload: yes
  notify:
    - restart elasticsearch container

- name: 'folders : create elasticsearch directorys'
  become: true
  file:
    path: '{{ item }}'
    state: directory
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    mode: 0770
  with_items:
    - '{{ elasticsearch_config }}'
    - '{{ elasticsearch_data }}'
    - '{{ elasticsearch_plugins }}'